parameters:
  resource: "commands/publish"
  from: "latest"
  to: "test"
  nameB:
    value: "value2"
    description: "description of nameB"

jobs:
  main:
    image: node:8
    requires: [~pr, ~commit]
    annotations:
      screwdriver.cd/displayName: foo
    steps:
      - echo: echo hoge
  detatched:
    image: node:8
    requires: []
    steps:
      - echo: echo hoge
