shared:
  image: node:14

annotations:
  screwdriver.cd/chainPR: true
 
jobs:
  build1:
    requires: [ ~commit, ~pr ]
    steps:
      - hello: echo "Hello build1"
  build2:
    requires: [ build1 ]
    steps:
      - hello: echo "Hello build2"
  det:
    requires: []
    steps:
      - hello: echo "Hello det"
